# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
 - nvm use 5
 - npm install
 - pod install --project-directory=ReactNativeStoreViewExample
script:
- set -o pipefail && xcodebuild test -workspace ReactNativeStoreViewExample/ios/ReactNativeStoreViewExample.xcworkspace -scheme ReactNativeStoreViewExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
